/* global */
// Data fixtures for Makmai e-commerce prototype.
(function () {
const BRANCHES = [
  { id: "khonkaen", name_th: "สาขาขอนแก่น", name_en: "Khon Kaen",
    addr_th: "ถ.มิตรภาพ ใจกลางเมือง", addr_en: "Mittraphap Rd, city center",
    hours: "08:00 – 20:00", phone: "043-XXX-XXX", open: true },
  { id: "kalasin",  name_th: "สาขากาฬสินธุ์", name_en: "Kalasin",
    addr_th: "ตลาดเช้า กาฬสินธุ์", addr_en: "Morning Market, Kalasin",
    hours: "09:00 – 19:00", phone: "043-XXX-XXX", open: true },
];

const CATEGORIES = [
  { id: "all",      th: "ทั้งหมด",      en: "All" },
  { id: "juice",    th: "น้ำสกัดเย็น",  en: "Cold-pressed" },
  { id: "smoothie", th: "สมูทตี้",      en: "Smoothies" },
  { id: "tea",      th: "ชา",           en: "Tea" },
  { id: "coffee",   th: "กาแฟ",         en: "Coffee" },
  { id: "fruit",    th: "ผลไม้",        en: "Fruit" },
  { id: "meal",     th: "Meal",          en: "Meal" },
  { id: "hpns",     th: "High Protein",  en: "High Protein" },
];

// Hue strings used by ProductCard to render placeholder gradient
// Real photography would replace these.
const P = (props) => ({ id: props.id, ...props });
const PRODUCTS = [

  // ── Cold-pressed (฿65) ───────────────────────────────────────────────
  P({ id: "vitamin-c", cat: "juice", th: "วิตามินซี", en: "Vitamin C",
      desc_th: "น้ำผลไม้รวม · วิตามินซีสูง · สดชื่น", desc_en: "Mixed fruit · high vitamin C · refreshing",
      price: 65, hue: "orange", badge: "NEW", featured: true,
      image: "/assets/Cold Pressed/วิตามินซี.jpg" }),
  P({ id: "immune-boost", cat: "juice", th: "เสริมภูมิคุ้มกัน", en: "Immune Boost",
      desc_th: "ผักผลไม้รวม · ต้านอนุมูลอิสระ", desc_en: "Greens & fruit blend · antioxidant",
      price: 65, hue: "green", badge: "SIGNATURE", featured: true,
      image: "/assets/Cold Pressed/เสริมภูมิคุ้มกัน.jpg" }),

  // ── Smoothies (฿85) ──────────────────────────────────────────────────
  P({ id: "kiwi-paradise", cat: "smoothie", th: "Kiwi Paradise", en: "Kiwi Paradise",
      desc_th: "กีวี่ มะนาว แอปเปิ้ล", desc_en: "Kiwi, lime, apple",
      price: 85, hue: "lime", featured: true,
      image: "/assets/Smoothie/Kiwi Paradise.jpg" }),
  P({ id: "bahama-mama", cat: "smoothie", th: "Bahama Mama", en: "Bahama Mama",
      desc_th: "ผลไม้เขตร้อน · หวานฉ่ำ", desc_en: "Tropical blend · sweet & juicy",
      price: 85, hue: "mango",
      image: "/assets/Smoothie/bahama mama.jpg" }),
  P({ id: "beach-bum", cat: "smoothie", th: "Beach Bum", en: "Beach Bum",
      desc_th: "สับปะรด มะม่วง กล้วย", desc_en: "Pineapple, mango, banana",
      price: 85, hue: "mango",
      image: "/assets/Smoothie/beach bum.jpg" }),
  P({ id: "blimey-lime", cat: "smoothie", th: "Blimey Lime", en: "Blimey Lime",
      desc_th: "มะนาว แอปเปิ้ลเขียว · สดชื่น", desc_en: "Lime, green apple · zingy",
      price: 85, hue: "lime",
      image: "/assets/Smoothie/blimey lime.jpg" }),
  P({ id: "blue-avocado", cat: "smoothie", th: "Blue Avocado", en: "Blue Avocado",
      desc_th: "อะโวคาโด บลูเบอร์รี่ นม", desc_en: "Avocado, blueberry, milk",
      price: 85, hue: "berry",
      image: "/assets/Smoothie/blue avocado.jpg" }),
  P({ id: "blueberry-bliss", cat: "smoothie", th: "Blueberry Bliss", en: "Blueberry Bliss",
      desc_th: "บลูเบอร์รี่ กล้วย โยเกิร์ต", desc_en: "Blueberry, banana, yogurt",
      price: 85, hue: "berry",
      image: "/assets/Smoothie/blueberry bliss.jpg" }),
  P({ id: "jerry-punch", cat: "smoothie", th: "Jerry Punch", en: "Jerry Punch",
      desc_th: "มิกซ์เบอร์รี่ · เปรี้ยวหวาน", desc_en: "Mixed berry · sweet & tangy",
      price: 85, hue: "berry",
      image: "/assets/Smoothie/jerry punch.jpg" }),
  P({ id: "mango-magic", cat: "smoothie", th: "Mango Magic", en: "Mango Magic",
      desc_th: "มะม่วง กล้วย นมมะพร้าว", desc_en: "Mango, banana, coconut milk",
      price: 85, hue: "mango",
      image: "/assets/Smoothie/mango magic.jpg" }),
  P({ id: "paradise-point", cat: "smoothie", th: "Paradise Point", en: "Paradise Point",
      desc_th: "ผลไม้เขตร้อน · ครีมมี่", desc_en: "Tropical fruits · creamy blend",
      price: 85, hue: "mango",
      image: "/assets/Smoothie/paradise point.jpg" }),
  P({ id: "peach-silk", cat: "smoothie", th: "Peach Silk", en: "Peach Silk",
      desc_th: "พีช แอปริคอต โยเกิร์ต", desc_en: "Peach, apricot, yogurt",
      price: 85, hue: "orange",
      image: "/assets/Smoothie/peach slik.jpg" }),
  P({ id: "strawberry-lime", cat: "smoothie", th: "Strawberry Lime", en: "Strawberry Lime",
      desc_th: "สตรอว์เบอร์รี่ มะนาว · สดชื่น", desc_en: "Strawberry, lime · vibrant",
      price: 85, hue: "berry",
      image: "/assets/Smoothie/strawberry lime.jpg" }),
  P({ id: "sunrise-sunset", cat: "smoothie", th: "Sunrise Sunset", en: "Sunrise Sunset",
      desc_th: "ส้ม แครอท มะม่วง", desc_en: "Orange, carrot, mango",
      price: 85, hue: "orange",
      image: "/assets/Smoothie/sunrise sunset.jpg" }),
  P({ id: "sunshine", cat: "smoothie", th: "Sunshine", en: "Sunshine",
      desc_th: "สับปะรด กล้วย ขมิ้น", desc_en: "Pineapple, banana, turmeric",
      price: 85, hue: "lime",
      image: "/assets/Smoothie/sunshine smoothies.jpg" }),

  // ── Tea (฿65) ────────────────────────────────────────────────────────
  P({ id: "cha-blue", cat: "tea", th: "ชาบลู", en: "Blue Tea",
      desc_th: "ดอกอัญชัน · หอมเย็น", desc_en: "Butterfly pea · floral & cool",
      price: 65, hue: "berry", featured: true,
      image: "/assets/Tea/ชาบลู.jpg" }),
  P({ id: "cha-peach", cat: "tea", th: "ชาพีช", en: "Peach Tea",
      desc_th: "ชาพีช · หอมหวาน", desc_en: "Peach tea · sweet & fragrant",
      price: 65, hue: "orange",
      image: "/assets/Tea/ชาพีช.jpg" }),
  P({ id: "cha-passionfruit", cat: "tea", th: "ชาเสาวรส", en: "Passionfruit Tea",
      desc_th: "เสาวรส · เปรี้ยวอมหวาน", desc_en: "Passionfruit · sweet-tart",
      price: 65, hue: "mango",
      image: "/assets/Tea/ชาเสาวรส.jpg" }),

  // ── Coffee (฿85) — เพิ่มได้เมื่อมีรูป ─────────────────────────────

  // ── Meal ─────────────────────────────────────────────────────────────
  P({ id: "wrap", cat: "meal", th: "Wrap", en: "Wrap",
      desc_th: "ห่อเต็มคำ · ไส้ตามชอบ", desc_en: "Hearty wrap · your choice of filling",
      price: 99, hue: "earth",
      image: "/assets/Meal/Wrap.jpg" }),
  P({ id: "greek-yo", cat: "meal", th: "Greek Yo", en: "Greek Yo",
      desc_th: "กรีกโยเกิร์ต · ผลไม้สด · แกรโนล่า", desc_en: "Greek yogurt · fresh fruit · granola",
      price: 89, hue: "mango", featured: true,
      image: "/assets/Meal/Greek Yo.jpg" }),
  P({ id: "garlic-bread", cat: "meal", th: "ขนมปังกะเทียม", en: "Garlic Bread",
      desc_th: "เนยกระเทียมสมุนไพร · อบสด", desc_en: "Herb garlic butter · freshly baked",
      price: 40, hue: "salad",
      image: "/assets/Meal/ขนมปังกะเทียม.jpg" }),
  P({ id: "nacho", cat: "meal", th: "Nacho", en: "Nacho",
      desc_th: "นาโชกรอบ · ซอสชีส · ซัลซ่า", desc_en: "Crispy nachos · cheese sauce · salsa",
      price: 99, hue: "orange",
      image: "/assets/Meal/nacho.jpg" }),
  P({ id: "tuna-salad", cat: "meal", th: "Tuna Salad", en: "Tuna Salad",
      desc_th: "สลัดทูน่า · ผักสด · น้ำสลัด", desc_en: "Tuna salad · fresh greens · dressing",
      price: 79, hue: "salad",
      image: "/assets/Meal/Tuna Salad.JPG" }),
  P({ id: "tuna-sandwich", cat: "meal", th: "Tuna Sandwich", en: "Tuna Sandwich",
      desc_th: "แซนวิชทูน่า · ผักกรอบ · มาโย", desc_en: "Tuna sandwich · crisp veggies · mayo",
      price: 45, hue: "earth",
      image: "/assets/Meal/Tuna Sandwich.JPG" }),

  // ── Smoothie (เพิ่ม) ────────────────────────────────────────────────
  P({ id: "avocado-smoothie", cat: "smoothie", th: "Avocado Smoothie", en: "Avocado Smoothie",
      desc_th: "อะโวคาโด นม น้ำผึ้ง", desc_en: "Avocado, milk, honey",
      price: 85, hue: "green",
      image: "/assets/Smoothie/Avocado.JPG" }),

  // ── Tea (เพิ่ม) ──────────────────────────────────────────────────────
  P({ id: "pure-matcha", cat: "tea", th: "Pure Matcha", en: "Pure Matcha",
      desc_th: "มัทฉะแท้ · เข้มข้น · ไม่มีน้ำตาล", desc_en: "Pure matcha · rich & unsweetened",
      price: 65, hue: "green", featured: true,
      image: "/assets/Tea/Pure Matcha.jpg" }),
  P({ id: "strawberry-matcha", cat: "tea", th: "Strawberry Matcha", en: "Strawberry Matcha",
      desc_th: "มัทฉะ สตรอว์เบอร์รี่ · หอมหวาน", desc_en: "Matcha & strawberry · sweet floral",
      price: 65, hue: "berry",
      image: "/assets/Tea/Strawberry Matcha.jpg" }),
  P({ id: "orange-matcha", cat: "tea", th: "Orange Matcha", en: "Orange Matcha",
      desc_th: "มัทฉะ ส้ม · สดชื่น เปรี้ยวนำ", desc_en: "Matcha & orange · bright & zesty",
      price: 65, hue: "orange",
      image: "/assets/Tea/Orange Matcha.jpg" }),

  // ── Coffee (฿85 basic · ฿95 special) ───────────────────────────────
  P({ id: "homsuwan-coffee", cat: "coffee", th: "Homsuwan Coffee", en: "Homsuwan Coffee",
      desc_th: "กาแฟซิกเนเจอร์ · สูตรพิเศษ", desc_en: "Signature blend · house special",
      price: 85, hue: "earth", badge: "SIGNATURE", featured: true,
      image: "/assets/Coffee/Homsuwan Coffee.jpg" }),
  P({ id: "iced-americano", cat: "coffee", th: "อเมริกาโน่เย็น", en: "Iced Americano",
      desc_th: "เอสเพรสโซ่ น้ำ น้ำแข็ง", desc_en: "Espresso, water, ice",
      price: 85, hue: "earth" }),
  P({ id: "iced-latte", cat: "coffee", th: "ลาเต้เย็น", en: "Iced Latte",
      desc_th: "เอสเพรสโซ่ นมสด น้ำแข็ง", desc_en: "Espresso, fresh milk, ice",
      price: 85, hue: "earth" }),
  P({ id: "iced-cappuccino", cat: "coffee", th: "คาปูชิโน่เย็น", en: "Iced Cappuccino",
      desc_th: "เอสเพรสโซ่ นมโฟม น้ำแข็ง", desc_en: "Espresso, milk foam, ice",
      price: 85, hue: "earth" }),
  P({ id: "iced-mocha", cat: "coffee", th: "มอคค่าเย็น", en: "Iced Mocha",
      desc_th: "เอสเพรสโซ่ ช็อกโกแลต นม", desc_en: "Espresso, chocolate, milk",
      price: 85, hue: "earth" }),
  P({ id: "orange-coffee", cat: "coffee", th: "กาแฟส้ม", en: "Orange Coffee",
      desc_th: "เอสเพรสโซ่ น้ำส้มคั้นสด · ซิตรัส", desc_en: "Espresso & fresh orange juice · citrusy",
      price: 95, hue: "orange",
      image: "/assets/Coffee/Orange Coffee.jpg" }),
  P({ id: "pineapple-coffee", cat: "coffee", th: "กาแฟสับปะรด", en: "Pineapple Coffee",
      desc_th: "เอสเพรสโซ่ น้ำสับปะรดสด · หวานอมเปรี้ยว", desc_en: "Espresso & fresh pineapple · sweet-tart",
      price: 95, hue: "lime" }),

  // ── Fruit (฿59) ──────────────────────────────────────────────────────
  P({ id: "apple", cat: "fruit", th: "แอปเปิ้ล", en: "Apple",
      desc_th: "แอปเปิ้ลสด · กรอบหวาน", desc_en: "Fresh apple · crisp & sweet",
      price: 59, hue: "lime", featured: true,
      image: "/assets/Fruit/Apple.JPG" }),
  P({ id: "orange-fruit", cat: "fruit", th: "ส้ม", en: "Orange",
      desc_th: "ส้มสด · วิตามินซีสูง", desc_en: "Fresh orange · high vitamin C",
      price: 59, hue: "orange",
      image: "/assets/Fruit/Orange.JPG" }),
  P({ id: "shinemuscat", cat: "fruit", th: "ชายน์มัสแคท", en: "Shine Muscat",
      desc_th: "องุ่นชายน์มัสแคท · หวานหอม", desc_en: "Shine Muscat grapes · sweet & aromatic",
      price: 59, hue: "lime",
      image: "/assets/Fruit/Shinemuscat.JPG" }),

  // ── High Protein No Sugar (฿145) ────────────────────────────────────
  P({ id: "golden-glow", cat: "hpns", th: "Golden Glow", en: "Golden Glow",
      desc_th: "High Protein · ไม่มีน้ำตาล · สีทอง", desc_en: "High protein · zero sugar · golden blend",
      price: 145, hue: "mango", featured: true,
      image: "/assets/High Protein No Sugar/Golden Glow Smoothie.jpg" }),
  P({ id: "ocean-boost", cat: "hpns", th: "Ocean Boost", en: "Ocean Boost",
      desc_th: "High Protein · ไม่มีน้ำตาล · สีฟ้า", desc_en: "High protein · zero sugar · ocean blue",
      price: 145, hue: "green",
      image: "/assets/High Protein No Sugar/Ocean Boost.jpg" }),
  P({ id: "pink-boost", cat: "hpns", th: "Pink Boost", en: "Pink Boost",
      desc_th: "High Protein · ไม่มีน้ำตาล · สีชมพู", desc_en: "High protein · zero sugar · pink power",
      price: 145, hue: "berry",
      image: "/assets/High Protein No Sugar/Pink Boost.jpg" }),
  P({ id: "ruby-berry", cat: "hpns", th: "Ruby Berry", en: "Ruby Berry",
      desc_th: "High Protein · ไม่มีน้ำตาล · รสเบอร์รี่", desc_en: "High protein · zero sugar · berry ruby",
      price: 145, hue: "berry",
      image: "/assets/High Protein No Sugar/Ruby Berry.jpg" }),
  P({ id: "velvet-cocoa", cat: "hpns", th: "Velvet Cocoa Shake", en: "Velvet Cocoa Shake",
      desc_th: "High Protein · ไม่มีน้ำตาล · โกโก้กำมะหยี่", desc_en: "High protein · zero sugar · velvety cocoa",
      price: 145, hue: "earth",
      image: "/assets/High Protein No Sugar/Velvet Cocoa Shake.jpg" }),
];

const HUE_GRADIENTS = {
  orange: ["#F0A06A", "#E07A2D"],
  green:  ["#8FC7A6", "#3B9162"],
  berry:  ["#E08F8E", "#B33A3A"],
  lime:   ["#D1E091", "#A0B85A"],
  mango:  ["#FCD279", "#E8A33D"],
  salad:  ["#B9D690", "#6B9F4F"],
  "salad-dark": ["#A2B57F", "#5A7A3F"],
  earth:  ["#D9B583", "#8B5A2A"],
  shot:   ["#FFB36B", "#C8651D"],
  turmeric:["#F5C44A", "#C99A1A"],
  "green-dark":["#6FB58A", "#1E6E40"],
};

window.MAKMAI_DATA = { BRANCHES, CATEGORIES, PRODUCTS, HUE_GRADIENTS };
})();
